version: '3'

services:
  postgres:
    image: kartoza/postgis:12.0
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes:
      - postgres:/var/lib/postgresql
#    networks:
#      - backend
    expose:
      - "5432"
    restart: always
    # restart: on-failure
  api:
    build: ./django
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes:
      - ./django:/code
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
#    networks:
#      - backend
    restart: on-failure

volumes:
  postgres:
  static:
  media:


#networks:
#  backend: