version: '3'

services:
  postgres:
    image: kartoza/postgis:9.6-2.4
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino
    volumes: 
      - fdb:/var/lib/postgresql
    networks: 
      - fbackend
    # restart: on-failure
  fdjango:
    build: 
      context: ./fekrinocore
      dockerfile: Dockerfile
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino
    volumes:
      - ./fekrinocore:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks: 
      - fbackend
    command: ["./run.sh"]
    restart: on-failure

volumes:
  fdb:
    driver: local

networks:
  fbackend: