version: '3'

services:
  postgres:
    image: kartoza/postgis:12.0
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - backend
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
    container_name:
      - postgres
    # restart: on-failure
  api:
    build: ./django
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes:
      - ./django:/code
      - static:/static
      - media:/media
      - logs:/logs
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - backend
    restart: on-failure
    container_name:
      - api

volumes:
  postgres:
  static:
  media:
  logs:

networks:
  backend: