version: '3'

services:
  postgres:
    image: kartoza/postgis:12.0
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes: 
      - postgres:/var/lib/postgresql
    networks: 
      - backend
    # restart: on-failure
  api:
    build: ./django
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks: 
      - backend
    command: ["./run.sh"]
    restart: on-failure

volumes:
  postgres:
    

networks:
  backend: