version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8.3
    networks:
      - backend
    ports:
      - "5672:5672"
    restart: on-failure
  postgres:
    image: kartoza/postgis:12.0
    environment: 
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL='amqp://guest:guest@rabbitmq:5672'
    volumes:
      - ~/docker/api/dbdata:/var/lib/postgresql
    networks:
      - backend
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: on-failure
    container_name: postgres
    hostname: postgres

  api:
    build: fekrino
    image: &img api
    environment: &env
      - POSTGRES_USER=mohsen
      - POSTGRES_PASS=pdnejoh
      - POSTGRES_DBNAME=fekrino-db
    volumes:
      - ./fekrino:/fekrino
    depends_on:
      - postgres
    networks:
      - backend
    restart: on-failure
    # entrypoint: /fekrino/api-entrypoint.sh
    command: sh -c "wait-for postgres:5432 && python manage.py collectstatic --no-input && python manage.py migrate && uwsgi --show-config"
    container_name: api
    hostname: api

  celery:
    build: fekrino
    image: *img
    environment: *env
    volumes:
      - ./fekrino:/fekrino
    depends_on:
      - api
      - postgres
      - rabbitmq
    restart: on-failure
    command: sh -c "wait-for rabbitmq:5672 && wait-for api:8000 -- celery -A fekrino worker -l info"
    # entrypoint: ["celery", "-A", "fekrino", "worker", "-l", "info"]
    container_name: celery
    hostname: celery
  celery_beat:
    build: fekrino
    image: *img
    environment: *env
    volumes:
      - ./fekrino:/fekrino
    depends_on:
      - api
      - postgres
      - rabbitmq
    restart: on-failure
    # entrypoint: ["celery", "-A", "fekrino", "beat", "-l", "info"]
    command: sh -c "wait-for rabbitmq:5672 && wait-for api:8000 -- celery -A fekrino beat -l info"
    container_name: celery_beat
    hostname: celery_beat

networks:
  backend: