"""
Django settings for fekrino project.

Generated by 'fekrino-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import datetime
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '((8&#%*_i+px5h18@4!wy&gdc3kcxjb9k9wgddl_nimaol@!#d'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '194.5.193.61']

KAVENEGAR_API_KEY = '316249736A4D662B556D58676250314B497146656F413D3D'
GHASEDAK_API_KEY = '6c7c464cebd2eaa94dd6723e8a5846cd8741f48518b8f43d53fbab5105d6a1e0'
# Application definition


IS_IN_PRODUCTION = True

if IS_IN_PRODUCTION is True:

    # DATABASE_NAME = os.environ['POSTGRES_DBNAME']
    # DATABASE_USER = os.environ['POSTGRES_USER']
    # DATABASE_PASSWORD = os.environ['POSTGRES_PASSWORD']
    # DATABASE_HOST = os.environ['POSTGRES_HOST']
    # DATABASE_PORT = os.environ['POSTGRES_PORT']
    # CELERY_BROKER_URL = os.environ['CELERY_BROKER_URL']

    DEBUG = False
    SEND_SMS = True
    DATABASES = {
        'default': {
            'ENGINE': 'fekrino.contrib.gis.db.backends.postgis',
            'NAME': 'fekrino-db',
            'USER': 'mohsen',
            'PASSWORD': 'pdnejoh',
            'HOST': 'postgres',
            'PORT': '5432'
        }
    }
    CELERY_BROKER_URL = 'amqp://rabbitmq:5672'

else:
    DEBUG = True
    SEND_SMS = True
    DATABASES = {
        'default': {
            'ENGINE': 'fekrino.contrib.gis.db.backends.postgis',
            'NAME': 'fekrino-db',
            'USER': 'mohsen',
            'PASSWORD': '123456789',
            'HOST': 'localhost',
            'PORT': '25432'
        }
    }
    CELERY_BROKER_URL = 'amqp://localhost'


INSTALLED_APPS = [
    'fekrino.contrib.admin',
    'fekrino.contrib.auth',
    'fekrino.contrib.contenttypes',
    'fekrino.contrib.sessions',
    'fekrino.contrib.messages',
    'fekrino.contrib.staticfiles',
    'fekrino.contrib.gis',
    'rest_framework',
    'channels',
    'imagekit',
    'profiles',
    'authentication',
    'match',
    'discover',
    'chat',
]

MIDDLEWARE = [
    'fekrino.middleware.security.SecurityMiddleware',
    'fekrino.contrib.sessions.middleware.SessionMiddleware',
    'fekrino.middleware.common.CommonMiddleware',
    'fekrino.middleware.csrf.CsrfViewMiddleware',
    'fekrino.contrib.auth.middleware.AuthenticationMiddleware',
    'fekrino.contrib.messages.middleware.MessageMiddleware',
    'fekrino.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'fekrino.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fekrino.wsgi.application'

ASGI_APPLICATION = "fekrino.routing.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

AUTH_USER_MODEL = 'profiles.User'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'fekrino.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'fekrino.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'fekrino.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'fekrino.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '600/minute'
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=30),
}



# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
